version: '3'
services:
  mkdocs:
    image: jssdocente/mkdocs-daw
    build:
      context: ./.docker
      dockerfile: dockerfile
      
    container_name: Mkdocs-pmdm2526
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true
    command: serve --dev-addr 0.0.0.0:8000 --dirtyreload
    environment:
      - WATCHDOG_USE_POLLING=true